### ISSUE TITLE
Open the Member Vetting to all with @progcode.org

### ISSUE THREAD

**Issue by rcscastillo** [ProgressiveCoders/functions#193]
#### Description
We have to open the Member Vetting to all those with ProgCode.org email. Right now, there are only four people doing vetting.

#### Problem

We should empower new volunteer staffers in having ownership to the community by opening it up to folks with @progcode meeting.

#### Benefit

Increase ownership and empowerment to volunteer staffers.

#### Plan

- [ ] consent
- [ ] Add all folks with progcode.org accounts

#### Decision Making

...

#### Reference link(s)

...

**Comment by jpb5013** [comment]
Yes, great suggestion, I support. For next steps I'd recommend we start trying to hammer out the volunteer staff onboarding/requirements, as I see a clear separation between this and general volunteers. I completely think anybody who wants to volunteer should be able though don't necessarily think that means everyone should immediately have an email. 

Some possible requirements, don't necessarily need all of them:
1) Participated in onboarding and 1:1 onboarding 
2) Has led community, app, volunteer staff, or network onboarding call
3) Has remained consistently active for at least (a month?) in Slack and on calls
4) Has created a GitHub issue 
5) Has contributed to a GitHub Wiki article 
6) Has contributed/(led development?) to a document which is included in the ProgCode Toolkit
7) Consent vote from existing volunteer staff and community supermajority 

There can likely be some gray area, for example someone who has been an app leader to a key common good service or spoke on behalf of ProgCode in the community/referred members/identified partners/etc.

**Comment by desmondjones** [comment]
I support this, and I also agree with Joe's idea of setting some requirements. Vetting is more effective when done from a community perspective, rather than a personal one.  A combination of the listed items lends to that perspective.

**Comment by rapicastillo** [comment]
Yes this is great! Maybe thisbis best for a separate issue as well

**Comment by StraubCreative** [comment]
@jpb5013 I think this is a really great start. I like your comment too @desmondjones to prioritize a communal approach to vetting

I'd like to see criteria items that outline "known affiliations" and "referred by". Including these criteria items would be beneficial to vetting teams and the community at large if new @progcode asset applicants were forced to be transparent about where they're coming from and who recommended them.

Otherwise, I feel, this vetting process is just a neutral "to-do" list of hoops to jump through, meaning anybody, with any agenda can not only acquire @progcode assets, but invite others with similar or shared agendas into administrative activities. In this way vetting becomes a stacked process.

**Comment by desmondjones** [comment]
The "requirements' Joe suggests are necessary to ensure that the person given access to the information is trusted.  Applications contain personal information which should be protected from the general public.  To that end, I am uncomfortable with the title of this issue, because it suggests that everyone in ProgCode would have access to member applications.

**Comment by rcscastillo** [comment]
@desmondjones Please do suggest a better title. I think we can word  it better.

**Comment by rcscastillo** [comment]
I'm closing this issue and will be creating a new one reflecting the need for guidelines and process for resource allotment.
