### ISSUE TITLE
Prog Code Network Diagram

### ISSUE THREAD

**Issue by dave-mahler** [ProgressiveCoders/functions#5]
I think it would be good to have a high level view of the network to help new volunteers see the big picture. I've started a draft of the diagram in draw.io here: https://drive.google.com/file/d/0B5Ot9MxA6oUIbUlvck9rWkhRQTg/view?usp=sharing

**Comment by jpb5013** [comment]
This is awesome, @dave-mahler! Think it's going to be a huge help. 

Couple initial thoughts:
- [ ] I think Operations supports lurkers and volunteers, however Audience outreach should have communications to them
- [ ] We should probably have another circle for non community members, which Audience Outreach would support
- [ ] Partner relations to projects should have bi-directional communication
- [ ] Legal should probably be a member of operation
- [ ] If possible Projects and Prog Code Network should be in the middle of the screen, to show them as the center
- [ ] Partner Organizations and Prog Code Network should have bi-directional support and community connection, Partners should have a one-way "is a member of" connection to Prog Code Network
- [ ] Partner Organizations should have a is a member of a supports connection to projects

Don't take anything as gospel, more of very quick thoughts

**Comment by dave-mahler** [comment]
This is awesome! Really helpful. I'll add these in soon!

**Comment by dave-mahler** [comment]
![dave notes jan 6](https://cloud.githubusercontent.com/assets/24927375/21732392/420c6806-d427-11e6-83c1-4479d9b120e7.jpg)

**Comment by dave-mahler** [comment]
![network functions as facilitation](https://cloud.githubusercontent.com/assets/24927375/21733984/1d2b54f4-d42f-11e6-9bf3-65bcc5c75e29.jpg)

1) the number of connections is insane
(and that's the point)
but in thinking about our role as network managers, I realized how many of our functions are ultimately about facilitating communication between different groups of people
and so I'm now toying around with a diagram that classifies channels and functional teams based on the groups that they connect
with channels or teams not limited to focusing on just one type of connection
do you think this could be an effective way of arranging things?

**Comment by dave-mahler** [comment]
Ok, before I get too crazy looking for technical solutions, here's a simple spreadsheet where we can start to flesh out these relationships

https://docs.google.com/spreadsheets/d/1-BsktO-CmalhGJh2T_NCGDvlchdckAyw7OlOWWvQ8WE/edit?usp=sharing

**Comment by mattmallon** [comment]
I'd like to copy over my comment from Slack so it doesn't get lost to the archive monsters before I add any further comments in this thread: 

That gets to another point that I've been thinking about... So a problem that I and some other new volunteers have had is figuring out how exactly to get involved in a project. Each project is independent and has its own way of doing things, which isn't necessarily a problem, but it gets to be an issue when I don't know _how_ they do things or _where_ to find out. I'm crazy about drawing analogies between organizing and coding, because I am an über-nerd, so I was thinking on comparing the prog code network to internet networking, and the stuff I learned from my networks class in college. So the internet is composed of 5 layers -- one of them the physical layer of infrastructure, another the application layer of software, etc. Each layer is a black box, and the other layers are completely ignorant of the inner workings of the others, meaning that you could swap out an entire layer of the internet and replace it with something else, and it would still work. *But* the reason why that works is because each layer exposes a public interface, which the other layers expect to be in place so they can interact. 

That reminded me a lot of prog code. Each project is sort of its own black box, and the larger network shouldn't be concerned with the inner workings of each project. However, it can be difficult for the larger network and the black-boxed projects to interact when there is no shared public interface for the projects. That's what I would LOVE to see. Let's say each project has a pinned google doc or something, with answers to a set of questions containing info that any volunteer in that project would need. Stuff like: "What tool(s) do you use for project management? Can you provide a link so volunteers can see the current state of the project?" and "What coding languages, frameworks, etc. does your project use?" The types of things that any project, if it's going to function properly, needs to have, and that both new and existing volunteers would need to reference if they wanted to work on the project/figure out if it's a good fit for them. It would require very little overhead on the part of project leaders, but would be so helpful for new volunteers in a project. 

Maybe it'd be helpful to think of the "layers" of prog code -- the network itself, the staff, the projects, the individual volunteers, etc. -- and how they interact, what the public interfaces need to be for them to interact successfully.

**Comment by mattmallon** [comment]
So my comment touched on a few different interfaces: 

Staff --> Project Leaders: A starting template of questions that each project would need to answer so volunteers are informed. 

Project leaders --> Volunteers: Their answers to the questions, possibly with additional information not in the template, via a link pinned to the channel. 

Volunteers --> Projects: that volunteers access the link and read the answers before asking any questions that already have been answered. If each (or most) channels follow the same practice, this should make it easy for new volunteers to know where to go for those basic questions they have.

**Comment by rapi-progcode** [comment]
@dave-mahler how's everything here?

**Comment by dave-mahler** [comment]
@rapi-progcode this has lost some steam. If you think this is still valuable I can put some more time into it, but I think it would be good for us to first ask what use we'd put this to. It's very time consuming to make these diagrams, so I want to make sure that time will be worth it

**Comment by rapi-progcode** [comment]
No worries! If it has lost steam totally fine, means that it's not
primetimed for pilot yet. :) Thanks for starting this and will close this
as well.

**Comment by rapi-progcode** [comment]
Closing pilot. If anyone wants to pick this up in the future, please re-open.
