### ISSUE TITLE
Member Updates on Airtable

### ISSUE THREAD

**Issue by dave-mahler** [ProgressiveCoders/functions#69]
As a staff member I want to keep track of member skills so that I can connect people to projects they'd be interested in / have relevant skills for.

**Comment by dave-mahler** [comment]
@WoobieTuesday @desmondjones @rapicastillo let's kickstart this conversation here. What info will be important to share with the community about partners? What differentiates partners from projects? 

For instance, we should certainly include any channels that partners have open, including projects related to that partner. Website also seems good to include. What else?

**Comment by dave-mahler** [comment]
Here's a link to the airtable we discussed a few weeks ago: https://airtable.com/invite/l?inviteId=invjxBUT5HZeyOz44&inviteToken=249c3c6a57b5177fb436440e8a34494a

And this is the sheet we used to keep track of categories of skills/interests: https://docs.google.com/spreadsheets/d/19pYRnNR2_Kf2Kob7ruH5hT0uLl9mtyEkbRdunkWowdc/edit?usp=sharing

**Comment by dave-mahler** [comment]
Any objections to me proposing this work at the meeting this Sunday? @desmondjones @WoobieTuesday

**Comment by desmondjones** [comment]
Inasmuch as 1:1 interviews are not conducted with each member, I am concerned with the purpose this is intended to serve.  Will this be an optional record?

**Comment by dave-mahler** [comment]
Totally optional. Remember that we also discussed asking for consent for this info to be shared internally of they want projects suggested to them

**Comment by WoobieTuesday** [comment]
1. Even though not all members choose to attend a 1:1, it would help us match up those who do with projects looking for that member's particular skill set or matching their interest. It would also help us find volunteers who possess a skill set which could help address an app partner's pain point during those 1:1 app partner onboarding.   

1. Another category which would be useful to include is a rough estimate of the amount of time that a member estimates he/she may be available to help out. 

1. I also see a possible alternative use to this form. I always take notes during onboarding calls to help trigger my memory when somebody possessing a specialized skill or interest comes along around the same time that a project team is looking for that particular skill. Is it necessary to ask them to opt out of the form if information is being freely given in a public forum and is not being shared within the Network?

1. The Google Spreadsheet of categories of skills/interests was slapped together in about 10 minutes during a very quick brainstorming session. It includes lots of activist activities which could be more broadly grouped, and it's very light on the tech stacks, languages and platforms that coders use. It would be more useful if stacks, languages and platforms were specified so that they could be matched up with a project on the list which is looking for vols with those skills. 

@dave-mahler @desmondjones I do not have a problem with submitting this for a vote at the next Partner Meeting if we can address those questions during the discussion.

**Comment by jpb5013** [comment]
This is community member facing, not partner-facing, right? Though I guess it stems both categories. @jlegrone should be aware from a partner perspective.

And would this be separate to the [existing registration](https://airtable.com/shraBEItZa0sYiMB0) or simply added to it?

Either way, I think it's a great exercise to capture more specific information from the non-technical perspective. From the technical side, I think the bigger current need is simply utilizing the information we're already collecting. For the time available side of things, I'd recommend to keep that into non-specific buckets (e.g., not much, some, a ton) as we don't want to scare people off and it's not like we'll be enforcing their estimates anyway. A better question may be along the lines of how motivated they are to support ProgCode. Keeping the entry barriers low will encourage people to get hooked on that good ProgCode Crack ;)

**Comment by WoobieTuesday** [comment]
I've since spoken with @tktino who has some really great ideas about a way to automate this form using .csv, similar to the solution he and @rthbound have been working on to auto-update the Airtable channel list.

**Comment by jpb5013** [comment]
Also want to lump this issue I created into this discussion here https://github.com/ProgressiveCoders/functions/issues/123
