### ISSUE TITLE
New Members Not Added to Cohort Channel, Not Invited to 1:1 Session

### ISSUE THREAD

**Issue by WoobieTuesday** [ProgressiveCoders/functions#94]
### Current Process:

1. New member attends onboarding call **before** joining Slack; **_or_** 
1. New member attends onboarding call **after** joining Slack.
1. At conclusion of Onboarding Call, all members already in the Slack are added to monthly Onboarding cohorts channel & invited to set up 1:1 onboarding buddy call.
1. At conclusion of Onboarding Call, members _not_ already in the Slack are not added to the monthly Onboarding cohorts channel.
1. Members not added to Onboarding cohorts channel do not get invite to 1:1 onboarding buddy meeting.

### Problem:
In the case of 4 & 5, it is the up to the staffer conducting the onboarding session to try to locate the members who attended the initial onboarding call when they finally join the Slack. This is often difficult if:

- New user doesn't join Slack for a week or so after initial onboarding call;
- New user joins Slack and uses a creative handle which doesn't reflect their real name (making it more difficult to determine if they have/have not attended an onboarding call); or
- New user joins Slack at a time when the staffer who conducted the onboarding session is not watching #introductions channel. 

### Proposed Solution:

During the onboarding call, after staff introductions, the staffer conducting the onboarding call posts a Google Doc in the chat and asks that attendees not already in the Slack list their full name, email address and intended Slack Handle so that once the invite is sent, members from the onboarding team can more easily locate them and add them to the onboarding cohort channel.

**Comment by jpb5013** [comment]
Really good point, @WoobieTuesday! Do you think we'd be able to hook this into existing processes instead of creating a new sheet, either updating Airtable on the fly, asking them to DM email address for immediate invite, or at least updating AIrtable record that they attended onboarding (we should probably be tracking this, important information). I believe anyone on one of these calls has already registered, so their information should already be available, but for friends who haven't we should also ask them to do so.

This also calls to attention the need to have at least _some_ standard processes for onboarding, though still encouraging experimentation (for example, @dave-mahler process of going through the channel list and having them add is awesome). We'll also need a mechanism for tracking our experimentations so that we update existing processes accordingly. Some current one's I see include:

- [ ] Confirming that they've already registered, sending them to [Prog Code](www.progcode.co) to do so if not
- [ ] Onboarding lead introducing themselves and giving their personal story
- [ ] Briefly discussing Prog Code's background and goals (non-partisan, non-hierarchical, get money out of politics)
- [ ] Discussing Prog Code culture, get their feedback on ideal culture and challenges they've experienced in the past
- [ ] Having them review Airtable channel list and having them add channels based on their interests
- [ ] Introducing them to Airtable projects and functions boards, show where to get started with training
- [ ] Introducing them to resources and training available
- [ ] Providing an overview for onboarding buddy process
- [ ] Doing round-robin introductions asking who they are, what brings them here, and what goals they have
- [ ] Updating their Airtable information with anything missed
- [ ] Asking if they've had any challenges so far we can help support
- [ ] Inviting them to their cohort channel

Many of these could be coordinated by a second staffer supporting the call rather than leading it

**Comment by WoobieTuesday** [comment]
@jpb5013 

> Do you think we'd be able to hook this into existing processes instead of creating a new sheet, either updating Airtable on the fly, asking them to DM email address for immediate invite, or at least updating AIrtable record that they attended onboarding (we should probably be tracking this, important information). I believe anyone on one of these calls has already registered, so their information should already be available, but for friends who haven't we should also ask them to do so.

I hope so!! It would be an infinitely more sleek solution. I especially like your suggestions of having a second staffer updating the Airtable on the fly. Since I'm always taking notes anyway, am happy to be that second staffer on as many of the onboarding calls I can attend!

I also love the onboarding checklist. It's a really helpful roadmap. 👍 👍 from this onboarder.

**Comment by desmondjones** [comment]
One question regarding 1 & 2 in the original Issue:  Are we considering that some of these people might not have completed an application for an invite to the ProgCode Slack?  That has happened on a few occasions.  For that reason, it would be important to have a document that contains their info which might be cross-checked against a later-submitted application.

**Comment by WoobieTuesday** [comment]
@desmondjones Yes, I think that Item #1 is inclusive of people who have and have not joined Slack. If they have not even submitted an application, they would have to do that before being added to the Slack and there would be no need for an additional document to contain their information because it will all be available in the application once they do so. We just have to remind the people who have not yet submitted an application that they can do so trough the link on the front page of the website.

**Comment by WoobieTuesday** [comment]
@jpb5013 Consent to continue exploring this method was granted by the community Mar 19 2017 and @rthbound has completed the Action Item for Issue #132. It has been working beautifully. 

Tonight (Mar 23) is my first Member Onboarding 1:1 and Group Member Onboarding call since  Members tab was added by @rthbound  to the Airtable Masterform and seamlessly auto-populated via member profiles with the names and handles of existing ProgCode Slack community members.  (Thank you @rthbound!)

In tonight's Group Member Onboarding Call I will implement add columns to the Members Tab in the Airtable Form to check off the items you've wisely suggested in your [comment](https://github.com/ProgressiveCoders/functions/issues/94#issuecomment-284230995) above. 

Will keep you posted and update the Operations Team in the Mar 26 Operations Meeting. 

Thanks!

**Comment by desmondjones** [comment]
Many thanks, @rthbound!

**Comment by jpb5013** [comment]
Woo hoo! Looking forward to learning about this. Thanks, Tad!

**Comment by rcscastillo** [comment]
We had one instance from the last onboarding from the onboarding call if they asked for email addresses and handles. 

One person slipped in the cracks. When the person named her intro, she did not say her first name, and we couldn't find her. 

We can close it!

Hard to find their profiles. We get the 99%.
